# Generated by Django 5.2.12 on 2026-03-15 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlturadoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Altura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
                ('Porcentagem', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadodeMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Em_Movimento', models.BooleanField(default=False)),
                ('Velocidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('TempodeServico', models.IntegerField()),
                ('Nobanco', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressaodoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pressao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PressaoPneus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pressao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusdeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Em_Operacao', models.BooleanField(default=False)),
                ('Tempo_de_Operacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TempUmi_Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperatura', models.FloatField()),
                ('Umidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadedeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.marca')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperatura', models.FloatField()),
                ('Maquina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_tcc.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Colheitadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlturadoCorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.alturadocorte')),
                ('Combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.combustivel')),
                ('EstadodeMovimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.estadodemovimento')),
                ('Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.modelo')),
                ('Operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.operario')),
                ('PressaodoCorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.pressaodocorte')),
                ('PressaoPneus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.pressaopneus')),
                ('StatusdeOperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.statusdeoperacao')),
                ('TemperaturaMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.temperaturamaquina')),
                ('TempUmi_Ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.tempumi_ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Transbordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capacidade', models.FloatField()),
                ('Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.modelo')),
            ],
        ),
        migrations.AddField(
            model_name='pressaopneus',
            name='UnidadedeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_tcc.unidadedemedida'),
        ),
        migrations.AddField(
            model_name='pressaodocorte',
            name='UnidadedeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_tcc.unidadedemedida'),
        ),
        migrations.AddField(
            model_name='alturadocorte',
            name='UnidadedeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_tcc.unidadedemedida'),
        ),
    ]
