# Generated by Django 5.2 on 2026-03-19 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraTelemetria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maquina_id', models.CharField(max_length=50)),
                ('temperatura', models.FloatField()),
                ('vibracao', models.FloatField()),
                ('rpm', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
