# Generated by Django 5.2 on 2026-03-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0002_leituratelemetria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alturadocorte',
            options={'verbose_name': 'Altura de Corte', 'verbose_name_plural': 'Alturas de Corte'},
        ),
        migrations.AlterModelOptions(
            name='colheitadeira',
            options={'verbose_name': 'Colheitadeira', 'verbose_name_plural': 'Colheitadeiras'},
        ),
        migrations.AlterModelOptions(
            name='combustivel',
            options={'verbose_name': 'Combustível', 'verbose_name_plural': 'Combustíveis'},
        ),
        migrations.AlterModelOptions(
            name='estadodemovimento',
            options={'verbose_name': 'Estado de Movimento', 'verbose_name_plural': 'Estados de Movimento'},
        ),
        migrations.AlterModelOptions(
            name='leituratelemetria',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Leitura de Telemetria', 'verbose_name_plural': 'Leituras de Telemetria'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='operario',
            options={'verbose_name': 'Operário', 'verbose_name_plural': 'Operários'},
        ),
        migrations.AlterModelOptions(
            name='pressaodocorte',
            options={'verbose_name': 'Pressão de Corte', 'verbose_name_plural': 'Pressões de Corte'},
        ),
        migrations.AlterModelOptions(
            name='pressaopneus',
            options={'verbose_name': 'Pressão dos Pneus', 'verbose_name_plural': 'Pressões dos Pneus'},
        ),
        migrations.AlterModelOptions(
            name='statusdeoperacao',
            options={'verbose_name': 'Status de Operação', 'verbose_name_plural': 'Status de Operação'},
        ),
        migrations.AlterModelOptions(
            name='temperaturamaquina',
            options={'verbose_name': 'Temperatura da Máquina', 'verbose_name_plural': 'Temperaturas das Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='tempumi_ambiente',
            options={'verbose_name': 'Temperatura e Umidade do Ambiente', 'verbose_name_plural': 'Temperaturas e Umidades do Ambiente'},
        ),
        migrations.AlterModelOptions(
            name='transbordo',
            options={'verbose_name': 'Transbordo', 'verbose_name_plural': 'Transbordos'},
        ),
        migrations.AlterModelOptions(
            name='unidadedemedida',
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AlterField(
            model_name='alturadocorte',
            name='Altura',
            field=models.FloatField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='alturadocorte',
            name='UnidadedeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='AlturadoCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.alturadocorte', verbose_name='Altura de Corte'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='Combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.combustivel', verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='EstadodeMovimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.estadodemovimento', verbose_name='Estado de Movimento'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='Modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='Operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.operario', verbose_name='Operário'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='PressaoPneus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.pressaopneus', verbose_name='Pressão dos Pneus'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='PressaodoCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.pressaodocorte', verbose_name='Pressão de Corte'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='StatusdeOperacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.statusdeoperacao', verbose_name='Status de Operação'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='TempUmi_Ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.tempumi_ambiente', verbose_name='Temp./Umidade Ambiente'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='TemperaturaMaquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.temperaturamaquina', verbose_name='Temperatura da Máquina'),
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='Porcentagem',
            field=models.FloatField(verbose_name='Porcentagem (%)'),
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='Tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='estadodemovimento',
            name='Em_Movimento',
            field=models.BooleanField(default=False, verbose_name='Em Movimento'),
        ),
        migrations.AlterField(
            model_name='estadodemovimento',
            name='Velocidade',
            field=models.FloatField(verbose_name='Velocidade (km/h)'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='maquina_id',
            field=models.CharField(max_length=50, verbose_name='ID da Máquina'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='recebido_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recebido em'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='rpm',
            field=models.IntegerField(verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='temperatura',
            field=models.FloatField(verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp do Sensor'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='vibracao',
            field=models.FloatField(verbose_name='Vibração'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='Nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='Nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='Nobanco',
            field=models.BooleanField(default=True, verbose_name='No Banco'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='Nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='TempodeServico',
            field=models.IntegerField(verbose_name='Tempo de Serviço (anos)'),
        ),
        migrations.AlterField(
            model_name='pressaodocorte',
            name='Pressao',
            field=models.FloatField(verbose_name='Pressão'),
        ),
        migrations.AlterField(
            model_name='pressaodocorte',
            name='UnidadedeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='pressaopneus',
            name='Pressao',
            field=models.FloatField(verbose_name='Pressão'),
        ),
        migrations.AlterField(
            model_name='pressaopneus',
            name='UnidadedeMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.unidadedemedida', verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='statusdeoperacao',
            name='Em_Operacao',
            field=models.BooleanField(default=False, verbose_name='Em Operação'),
        ),
        migrations.AlterField(
            model_name='statusdeoperacao',
            name='Tempo_de_Operacao',
            field=models.FloatField(verbose_name='Tempo de Operação (h)'),
        ),
        migrations.AlterField(
            model_name='temperaturamaquina',
            name='Maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.modelo', verbose_name='Modelo da Máquina'),
        ),
        migrations.AlterField(
            model_name='temperaturamaquina',
            name='Temperatura',
            field=models.FloatField(verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='tempumi_ambiente',
            name='Temperatura',
            field=models.FloatField(verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='tempumi_ambiente',
            name='Umidade',
            field=models.FloatField(verbose_name='Umidade (%)'),
        ),
        migrations.AlterField(
            model_name='transbordo',
            name='Capacidade',
            field=models.FloatField(verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='transbordo',
            name='Modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_tcc.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='unidadedemedida',
            name='Nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
