# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0003_verbose_names_e_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='Modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='Combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.combustivel', verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='TempUmi_Ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.tempumi_ambiente', verbose_name='Temp./Umidade Ambiente'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='TemperaturaMaquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.temperaturamaquina', verbose_name='Temperatura da Máquina'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='Operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.operario', verbose_name='Operário'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='StatusdeOperacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.statusdeoperacao', verbose_name='Status de Operação'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='EstadodeMovimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.estadodemovimento', verbose_name='Estado de Movimento'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='PressaoPneus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.pressaopneus', verbose_name='Pressão dos Pneus'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='AlturadoCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.alturadocorte', verbose_name='Altura de Corte'),
        ),
        migrations.AlterField(
            model_name='colheitadeira',
            name='PressaodoCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_tcc.pressaodocorte', verbose_name='Pressão de Corte'),
        ),
    ]
