# Generated by Django 5.2 on 2026-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0005_indices_leitura_telemetria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituratelemetria',
            name='maquina_id',
            field=models.CharField(max_length=50, verbose_name='ID da Máquina'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp do Sensor'),
        ),
    ]
