# Generated by Django 5.2 on 2026-09-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0012_organization_machine_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituratelemetria',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='api_tcc.machine', verbose_name='Machine (FK)'),
        ),
    ]
