# Generated by Django 6.0.7 on 2026-09-11 14:02
# Modified by S1-T5: added RunPython backfill for device_id and message_id
# before applying unique_together constraint.

from django.db import migrations, models


def backfill_device_id_message_id(apps, schema_editor):
    """
    Popula device_id e message_id para todas as leituras existentes.

    Regras de backfill (conservadoras — não alteram identidade):
    - device_id ← maquina_id.strip().upper()  (mesmo fallback do serviço)
    - message_id ← str(id)  (UUID da linha — cada linha histórica = mensagem única)

    Decisão: usar o UUID da linha como message_id de backfill é seguro porque:
    - Dados históricos já foram persistidos; não haverá reenvio com o mesmo UUID.
    - Preserva a unicidade da constraint (device_id, message_id).
    - Não mascara dados inválidos: maquina_id vazio vira device_id='DESCONHECIDO'.
    """
    LeituraTelemetria = apps.get_model('api_tcc', 'LeituraTelemetria')
    batch_size = 500
    leituras = list(LeituraTelemetria.objects.filter(device_id=''))

    updated = []
    for leitura in leituras:
        raw_id = str(leitura.maquina_id or '').strip().upper()
        leitura.device_id = raw_id if raw_id else 'DESCONHECIDO'
        leitura.message_id = str(leitura.id)
        updated.append(leitura)

    # bulk_update em batches para não travar o banco
    for i in range(0, len(updated), batch_size):
        LeituraTelemetria.objects.bulk_update(
            updated[i:i + batch_size],
            ['device_id', 'message_id'],
        )


def reverse_backfill(apps, schema_editor):
    """Reverso: limpa device_id e message_id (volta para strings vazias)."""
    LeituraTelemetria = apps.get_model('api_tcc', 'LeituraTelemetria')
    LeituraTelemetria.objects.all().update(device_id='', message_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0013_leituratelemetria_machine_fk'),
    ]

    operations = [
        # 1. Criar SyncCursor antes de qualquer alteração em LeituraTelemetria
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Identificador do dispositivo. UNIQUE: um dispositivo = um cursor.', max_length=100, unique=True, verbose_name='Device ID')),
                ('last_acked_sequence', models.BigIntegerField(default=0, help_text='Maior sequence_number já confirmado para este device_id. Nunca retrocede.', verbose_name='Último Sequence Confirmado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sync Cursor',
                'verbose_name_plural': 'Sync Cursors',
                'ordering': ['device_id'],
            },
        ),
        # 2. Adicionar device_id com default='' temporário (será preenchido pelo backfill)
        migrations.AddField(
            model_name='leituratelemetria',
            name='device_id',
            field=models.CharField(db_index=True, default='', help_text='Identificador do hardware de origem. Fallback: maquina_id normalizado.', max_length=100, verbose_name='Device ID'),
            preserve_default=False,
        ),
        # 3. Adicionar message_id com default='' temporário
        migrations.AddField(
            model_name='leituratelemetria',
            name='message_id',
            field=models.CharField(default='', help_text='Identidade lógica da mensagem. Com device_id, forma a chave de idempotência.', max_length=255, verbose_name='Message ID'),
            preserve_default=False,
        ),
        # 4. Campos adicionais (com defaults — não precisam de backfill)
        migrations.AddField(
            model_name='leituratelemetria',
            name='payload_hash',
            field=models.CharField(blank=True, help_text='SHA-256 (hex, 64 chars) do payload original. Rastreabilidade — NÃO é chave de idempotência.', max_length=64, null=True, verbose_name='Payload Hash'),
        ),
        migrations.AddField(
            model_name='leituratelemetria',
            name='sequence_number',
            field=models.BigIntegerField(default=0, help_text='Número de sequência monotônico para cursor de sincronização.', verbose_name='Sequence Number'),
        ),
        migrations.AddField(
            model_name='leituratelemetria',
            name='source',
            field=models.CharField(default='api', help_text='Origem da telemetria: api, simulador, mqtt, gateway.', max_length=50, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='leituratelemetria',
            name='sync_status',
            field=models.CharField(default='sincronizado', help_text='Estado: sincronizado (ingestão direta), pendente (offline — Semana 8).', max_length=20, verbose_name='Status de Sincronização'),
        ),
        migrations.AddField(
            model_name='leituratelemetria',
            name='transport',
            field=models.CharField(default='http', help_text='Protocolo de transporte: http, mqtt, esp-now.', max_length=50, verbose_name='Transporte'),
        ),
        # 5. Semântica explicitada nos verbose_name (timestamp = event_time, recebido_em = ingested_at)
        migrations.AlterField(
            model_name='leituratelemetria',
            name='recebido_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recebido em (ingested_at)'),
        ),
        migrations.AlterField(
            model_name='leituratelemetria',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Timestamp do Sensor (event_time)'),
        ),
        # 6. Backfill: popular device_id e message_id ANTES da unique_together
        migrations.RunPython(
            backfill_device_id_message_id,
            reverse_code=reverse_backfill,
        ),
        # 7. Aplicar unique_together APÓS backfill (dados já consistentes)
        migrations.AlterUniqueTogether(
            name='leituratelemetria',
            unique_together={('device_id', 'message_id')},
        ),
        # 8. Índice composto para queries de cursor de sincronização
        migrations.AddIndex(
            model_name='leituratelemetria',
            index=models.Index(fields=['device_id', 'sequence_number'], name='api_tcc_lei_device__e12348_idx'),
        ),
    ]
