# Generated by Django 5.2 on 2026-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0014_telemetria_identity_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Marca explicitamente dados criados para demonstração pública controlada.', verbose_name='Machine de demonstração'),
        ),
    ]
