# Generated by Django 5.2 on 2026-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0015_machine_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituratelemetria',
            name='trust_score',
            field=models.FloatField(blank=True, help_text='Score heuristico 0..1 calculado na ingestao; null indica dado historico nao pontuado.', null=True, verbose_name='Trust Score'),
        ),
    ]
