# Generated by Django 5.2 on 2026-09-21 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0016_leituratelemetria_trust_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDataHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score_medio', models.FloatField(default=0.0, help_text='EMA normalizada 0..1 calculada a partir das leituras pontuadas.', verbose_name='Trust Score medio')),
                ('ultima_atualizacao', models.DateTimeField(db_index=True, help_text='Timestamp da ultima leitura considerada no MachineDataHealth.', verbose_name='Ultima atualizacao')),
                ('leituras_analisadas', models.PositiveIntegerField(default=0, help_text='Quantidade de leituras com trust_score incorporadas ao agregado.', verbose_name='Leituras analisadas')),
                ('sinais_de_alerta', models.JSONField(blank=True, default=dict, help_text='Sinais derivados dos motivos do trust_score individual.', verbose_name='Sinais de alerta')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_health', to='api_tcc.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Machine Data Health',
                'verbose_name_plural': 'Machine Data Health',
            },
        ),
    ]
