# Generated by Django 5.2 on 2026-09-21 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0017_machinedatahealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TEMP_ALTA', 'Temperatura alta'), ('VIBRACAO_ALTA', 'Vibracao alta'), ('ANOMALIA_ML', 'Anomalia ML'), ('TENDENCIA_RISCO', 'Tendencia de risco')], db_index=True, max_length=40)),
                ('severidade', models.CharField(choices=[('NORMAL', 'Normal'), ('ATENCAO', 'Atencao'), ('CRITICO', 'Critico')], db_index=True, default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], db_index=True, default='ABERTO', max_length=20)),
                ('trust_score_herdado', models.FloatField(blank=True, help_text='Trust Score copiado da leitura que originou o evento.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dados_contexto', models.JSONField(blank=True, default=dict)),
                ('leitura_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api_tcc.leituratelemetria', verbose_name='Leitura de origem')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api_tcc.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['machine', 'tipo', 'status', '-criado_em'], name='api_tcc_eve_machine_2b7faf_idx'), models.Index(fields=['machine', 'severidade', '-criado_em'], name='api_tcc_eve_machine_5acfc2_idx')],
            },
        ),
    ]
