# Generated by Django 5.2 on 2026-09-21 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0018_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(verbose_name='Texto da recomendacao')),
                ('acao_recomendada', models.TextField(verbose_name='Acao recomendada')),
                ('severidade', models.CharField(choices=[('NORMAL', 'Normal'), ('ATENCAO', 'Atencao'), ('CRITICO', 'Critico')], db_index=True, default='NORMAL', max_length=20)),
                ('confianca', models.FloatField(blank=True, help_text='Confianca da recomendacao em 0..1; null quando o pipeline atual nao produz score.', null=True, verbose_name='Confianca')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('EXECUTADA', 'Executada'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('outcome_texto', models.TextField(blank=True, null=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions_decididas', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='api_tcc.event', verbose_name='Event')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='api_tcc.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['machine', 'status', '-criado_em'], name='api_tcc_dec_machine_86e7f7_idx'), models.Index(fields=['machine', 'severidade', '-criado_em'], name='api_tcc_dec_machine_3b1f05_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confianca__isnull', True), models.Q(('confianca__gte', 0.0), ('confianca__lte', 1.0)), _connector='OR'), name='decision_confianca_0_1_or_null')],
            },
        ),
    ]
