# Generated by Django 5.2 on 2026-10-08 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0020_ml_anomaly_persistence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contexto', models.CharField(choices=[('VALIDACAO', 'Validação'), ('EVENTO', 'Evento'), ('DECISAO', 'Decisão'), ('SYNC', 'Sincronização')], db_index=True, max_length=20)),
                ('payload_referencia', models.JSONField(default=dict)),
                ('motivo', models.CharField(max_length=500)),
                ('tentativas', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolvido', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Entrada da Dead Letter Queue',
                'verbose_name_plural': 'Entradas da Dead Letter Queue',
                'ordering': ['-resolvido', '-criado_em'],
                'indexes': [models.Index(fields=['resolvido', '-criado_em'], name='api_tcc_dea_resolvi_79834c_idx'), models.Index(fields=['contexto', '-criado_em'], name='api_tcc_dea_context_25730b_idx')],
            },
        ),
    ]
