# Generated by Django 5.2 on 2026-10-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0021_deadletterentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadletterentry',
            options={'ordering': ['resolvido', '-criado_em'], 'verbose_name': 'Entrada da Dead Letter Queue', 'verbose_name_plural': 'Entradas da Dead Letter Queue'},
        ),
    ]
