# Generated by Django 5.2 on 2026-10-09 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_MAPPINGS = [
    # Adaptadores simulados pedidos em S9-T2.
    ("case_ih_v1", "SPN_190", "engine.rpm", 1.0, "rpm", "0.99"),
    ("john_deere_v1", "engine_speed", "engine.rpm", 1.0, "rpm", "0.99"),
    # Compatibilidade com o payload legado produzido pelos simuladores atuais.
    ("fieldnode_simulator_v1", "temperatura", "engine.temperature", 1.0, "C", "0.90"),
    ("fieldnode_simulator_v1", "vibracao", "engine.vibration", 1.0, "g", "0.90"),
    ("fieldnode_simulator_v1", "rpm", "engine.rpm", 1.0, "rpm", "0.90"),
]


def seed_mappings(apps, schema_editor):
    FabricanteMapping = apps.get_model("api_tcc", "FabricanteMapping")
    for manufacturer, raw_parameter, canonical_parameter, factor, unit, confidence in DEFAULT_MAPPINGS:
        FabricanteMapping.objects.create(
            manufacturer=manufacturer,
            raw_parameter=raw_parameter,
            canonical_parameter=canonical_parameter,
            unit_conversion_factor=factor,
            mapping_version="v0.1",
            confidence=float(confidence),
            ativo=True,
        )


def unseed_mappings(apps, schema_editor):
    FabricanteMapping = apps.get_model("api_tcc", "FabricanteMapping")
    FabricanteMapping.objects.filter(
        manufacturer__in=[row[0] for row in DEFAULT_MAPPINGS],
        mapping_version="v0.1",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_tcc', '0023_event_priority_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricanteMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(db_index=True, max_length=100)),
                ('raw_parameter', models.CharField(max_length=100)),
                ('canonical_parameter', models.CharField(db_index=True, max_length=100)),
                ('unit_conversion_factor', models.FloatField(default=1.0)),
                ('mapping_version', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=1.0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['manufacturer', 'raw_parameter', '-mapping_version'],
                'indexes': [models.Index(fields=['manufacturer', 'raw_parameter', 'ativo'], name='api_tcc_fab_manufac_b06343_idx')],
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'raw_parameter', 'mapping_version'), name='uniq_fabricante_raw_mapping_version')],
            },
        ),
        migrations.CreateModel(
            name='RawTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(db_index=True, max_length=100)),
                ('raw_parameter', models.CharField(db_index=True, max_length=100)),
                ('raw_value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('source_protocol_simulado', models.CharField(max_length=80)),
                ('recebido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload_original', models.JSONField(default=dict)),
                ('quality', models.CharField(default='raw', max_length=40)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_telemetries', to='api_tcc.machine')),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_parameter', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('quality', models.CharField(default='mapped', max_length=40)),
                ('mapping_version', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('raw_telemetry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_telemetries', to='api_tcc.rawtelemetry')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='rawtelemetry',
            index=models.Index(fields=['machine', '-recebido_em'], name='api_tcc_raw_machine_f37dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtelemetry',
            index=models.Index(fields=['manufacturer', 'raw_parameter'], name='api_tcc_raw_manufac_c93c86_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicaltelemetry',
            constraint=models.UniqueConstraint(fields=('raw_telemetry', 'canonical_parameter'), name='uniq_canonical_per_raw_parameter'),
        ),
        migrations.RunPython(seed_mappings, unseed_mappings),
    ]
